"""
qd.gate — the go-live gate.

Real money is unreachable until walk-forward evidence says the signal works.
Not a warning, not a config flag — a hard block in the broker adapter, checked
before every live order.

The gate exists because of a specific, well-documented failure mode: a system
is built, the backtest looks good, the paper run looks fine, and it goes live on
the strength of a feeling that it is ready. The feeling is generated by the
effort already invested, not by the evidence. Anyone who has built one of these
knows the moment; the defence has to be structural, decided in advance, and
inconvenient to bypass — because it will be evaluated at exactly the moment
when its author most wants it gone.

Five conditions, all required:

  1. An edge proof exists, produced by research/evaluate.py.
  2. It covers enough OUT-OF-SAMPLE trades to mean anything.
  3. It stays positive at the STRESSED cost multiple, not just the friendly one.
  4. It is positive across the majority of walk-forward folds — an edge that
     lives in one lucky period is a period, not an edge.
  5. It is recent, and a paper run of real length agrees with it.

Tamper-evidence, not tamper-proofing: the proof carries a content hash, so
hand-editing a number invalidates it. Anyone with repository access can of
course regenerate a proof saying whatever they like. The hash defends against
the drifting-standards version of this problem — quietly nudging a threshold
after a disappointing result — rather than against a determined author. If you
find yourself editing this file to get past it, that is the signal it was
written to give you.
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
from dataclasses import asdict, dataclass, field
from datetime import datetime, timedelta
from typing import Any, Optional

from qd.config import Mode, Settings
from qd.types import UTC, ensure_utc, utcnow

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# Requirements
# ─────────────────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class Requirements:
    """The bar. Set once, before results are known.

    Chosen to be survivable rather than impressive: a system clearing these is
    not necessarily good, it is merely not obviously broken. Anything laxer
    would pass on noise — with 200 trades, an expectancy of +0.05R is barely
    distinguishable from zero, which is why the fold and cost conditions carry
    as much of the weight as the headline number.
    """
    min_oos_trades: int = 200
    min_expectancy_r: float = 0.05
    min_profit_factor: float = 1.15
    min_folds: int = 3
    min_positive_fold_ratio: float = 0.6
    stress_cost_mult: float = 2.0        # must survive costs at 2x the base model
    max_proof_age_days: int = 30
    min_paper_days: int = 20
    min_paper_trades: int = 30
    # Paper may underperform the backtest, but not by an implausible margin —
    # a large gap means the simulation is modelling something other than the
    # market the paper account is trading.
    max_paper_shortfall_r: float = 0.10


DEFAULT_REQUIREMENTS = Requirements()


# ─────────────────────────────────────────────────────────────────────────────
# Proof
# ─────────────────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class FoldResult:
    label: str
    trades: int
    expectancy_r: float
    profit_factor: float
    max_drawdown_pct: float = 0.0


@dataclass(frozen=True)
class EdgeProof:
    """The artefact research/evaluate.py emits. Only the walk-forward,
    out-of-sample numbers belong here — in-sample results prove nothing except
    that the parameters were chosen after seeing the data."""
    generated_at: datetime
    strategy_version: str
    data_start: str
    data_end: str
    oos_trades: int
    expectancy_r: float
    profit_factor: float
    max_drawdown_pct: float
    cost_mult: float
    stressed: dict[str, float] = field(default_factory=dict)   # cost_mult -> expectancy
    folds: tuple[FoldResult, ...] = ()
    notes: str = ""
    content_hash: str = ""

    def compute_hash(self) -> str:
        payload = {
            "generated_at": self.generated_at.isoformat(),
            "strategy_version": self.strategy_version,
            "oos_trades": self.oos_trades,
            "expectancy_r": round(self.expectancy_r, 6),
            "profit_factor": round(self.profit_factor, 6),
            "cost_mult": self.cost_mult,
            "stressed": {k: round(v, 6) for k, v in sorted(self.stressed.items())},
            "folds": [
                [f.label, f.trades, round(f.expectancy_r, 6)] for f in self.folds
            ],
        }
        blob = json.dumps(payload, sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(blob.encode()).hexdigest()[:32]

    def is_intact(self) -> bool:
        return bool(self.content_hash) and self.content_hash == self.compute_hash()

    def age(self, now: Optional[datetime] = None) -> timedelta:
        return (now or utcnow()) - self.generated_at

    def positive_fold_ratio(self) -> float:
        if not self.folds:
            return 0.0
        return sum(1 for f in self.folds if f.expectancy_r > 0) / len(self.folds)

    def expectancy_at(self, mult: float) -> Optional[float]:
        for k, v in self.stressed.items():
            if abs(float(k) - mult) < 1e-9:
                return v
        return None

    def to_json(self) -> str:
        d = asdict(self)
        d["generated_at"] = self.generated_at.isoformat()
        d["folds"] = [asdict(f) for f in self.folds]
        d["content_hash"] = self.compute_hash()
        return json.dumps(d, indent=2, sort_keys=True)

    def save(self, path: str) -> None:
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        with open(path, "w") as fh:
            fh.write(self.to_json())
        logger.info("edge proof written to %s (hash %s)", path, self.compute_hash())

    @classmethod
    def load(cls, path: str) -> Optional["EdgeProof"]:
        if not os.path.exists(path):
            return None
        try:
            with open(path) as fh:
                d = json.load(fh)
            folds = tuple(FoldResult(**f) for f in d.pop("folds", []))
            d["generated_at"] = ensure_utc(datetime.fromisoformat(d["generated_at"]))
            d["stressed"] = {str(k): float(v) for k, v in (d.get("stressed") or {}).items()}
            return cls(**d, folds=folds)
        except Exception as exc:                     # malformed proof = no proof
            logger.error("could not read edge proof at %s: %s", path, exc)
            return None


@dataclass(frozen=True)
class PaperRecord:
    """Live-ish results from the paper account, for the reality check."""
    days: int = 0
    trades: int = 0
    expectancy_r: float = 0.0
    profit_factor: float = 0.0
    start: Optional[datetime] = None
    end: Optional[datetime] = None

    @classmethod
    def from_portfolio(cls, portfolio, days: int) -> "PaperRecord":
        st = portfolio.stats()
        if not st.get("trades"):
            return cls(days=days)
        return cls(
            days=days,
            trades=int(st["trades"]),
            expectancy_r=float(st["expectancy_r"]),
            profit_factor=float(st["profit_factor"]),
        )


# ─────────────────────────────────────────────────────────────────────────────
# Verdict
# ─────────────────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class GateResult:
    allowed: bool
    reasons: tuple[str, ...] = ()
    passed: tuple[str, ...] = ()

    def explain(self) -> str:
        if self.allowed:
            return "LIVE ALLOWED — " + "; ".join(self.passed)
        return "LIVE BLOCKED:\n" + "\n".join(f"  - {r}" for r in self.reasons)


def check(
    mode: Mode,
    proof: Optional[EdgeProof],
    paper: Optional[PaperRecord] = None,
    req: Requirements = DEFAULT_REQUIREMENTS,
    now: Optional[datetime] = None,
) -> GateResult:
    """Evaluate whether live trading is permitted.

    Replay and paper always pass — the gate governs real money only.
    """
    if mode is not Mode.LIVE:
        return GateResult(True, passed=(f"mode={mode.value} (no real money at risk)",))

    now = ensure_utc(now or utcnow())
    fails: list[str] = []
    passes: list[str] = []

    if proof is None:
        return GateResult(False, reasons=(
            "no edge proof found — run `python -m qd.cli evaluate` to generate one",
        ))

    if not proof.is_intact():
        fails.append(
            f"edge proof hash mismatch (stored={proof.content_hash or 'none'}, "
            f"computed={proof.compute_hash()}) — the file was edited after generation"
        )
    else:
        passes.append("proof intact")

    age = proof.age(now)
    if age > timedelta(days=req.max_proof_age_days):
        fails.append(
            f"edge proof is {age.days}d old (max {req.max_proof_age_days}d) — "
            f"regenerate against recent data"
        )
    else:
        passes.append(f"proof {age.days}d old")

    if proof.oos_trades < req.min_oos_trades:
        fails.append(
            f"{proof.oos_trades} out-of-sample trades, need {req.min_oos_trades} "
            f"— too few to distinguish edge from luck"
        )
    else:
        passes.append(f"{proof.oos_trades} OOS trades")

    if proof.expectancy_r < req.min_expectancy_r:
        fails.append(
            f"expectancy {proof.expectancy_r:+.4f}R below {req.min_expectancy_r}R"
        )
    else:
        passes.append(f"expectancy {proof.expectancy_r:+.4f}R")

    if proof.profit_factor < req.min_profit_factor:
        fails.append(
            f"profit factor {proof.profit_factor:.3f} below {req.min_profit_factor}"
        )
    else:
        passes.append(f"PF {proof.profit_factor:.3f}")

    # Cost stress. An edge that only exists at optimistic costs is an artefact
    # of the cost model, and the live cost is never the optimistic one.
    stressed = proof.expectancy_at(req.stress_cost_mult)
    if stressed is None:
        fails.append(
            f"no result at {req.stress_cost_mult}x cost — stress the cost model "
            f"before trusting this"
        )
    elif stressed < 0:
        fails.append(
            f"expectancy {stressed:+.4f}R at {req.stress_cost_mult}x costs — "
            f"the edge is inside the spread"
        )
    else:
        passes.append(f"{stressed:+.4f}R at {req.stress_cost_mult}x costs")

    if len(proof.folds) < req.min_folds:
        fails.append(f"{len(proof.folds)} walk-forward folds, need {req.min_folds}")
    else:
        ratio = proof.positive_fold_ratio()
        if ratio < req.min_positive_fold_ratio:
            fails.append(
                f"only {ratio:.0%} of folds positive (need {req.min_positive_fold_ratio:.0%}) "
                f"— the result depends on which period you look at"
            )
        else:
            passes.append(f"{ratio:.0%} of {len(proof.folds)} folds positive")

    # Paper reality check.
    if paper is None or paper.days < req.min_paper_days:
        got = paper.days if paper else 0
        fails.append(f"{got} days of paper trading, need {req.min_paper_days}")
    elif paper.trades < req.min_paper_trades:
        fails.append(f"{paper.trades} paper trades, need {req.min_paper_trades}")
    else:
        shortfall = proof.expectancy_r - paper.expectancy_r
        if shortfall > req.max_paper_shortfall_r:
            fails.append(
                f"paper expectancy {paper.expectancy_r:+.4f}R trails backtest "
                f"{proof.expectancy_r:+.4f}R by {shortfall:.4f}R — the simulation "
                f"is not modelling what the account is actually trading"
            )
        else:
            passes.append(f"paper {paper.expectancy_r:+.4f}R over {paper.trades} trades")

    return GateResult(not fails, tuple(fails), tuple(passes))


def check_settings(
    settings: Settings,
    paper: Optional[PaperRecord] = None,
    req: Requirements = DEFAULT_REQUIREMENTS,
    now: Optional[datetime] = None,
) -> GateResult:
    """Gate check using the proof path from settings."""
    proof = EdgeProof.load(settings.proof_path) if settings.mode is Mode.LIVE else None
    return check(settings.mode, proof, paper, req, now)


class LiveTradingBlocked(RuntimeError):
    """Raised when a live order is attempted without a passing gate."""


def enforce(
    settings: Settings,
    paper: Optional[PaperRecord] = None,
    req: Requirements = DEFAULT_REQUIREMENTS,
) -> None:
    """Raise unless live trading is permitted. Called by the broker adapter on
    every live order — one check at startup would leave a system that passed
    once running for months on a stale verdict."""
    result = check_settings(settings, paper, req)
    if not result.allowed:
        raise LiveTradingBlocked(result.explain())


__all__ = [
    "Requirements", "DEFAULT_REQUIREMENTS", "EdgeProof", "FoldResult",
    "PaperRecord", "GateResult", "check", "check_settings", "enforce",
    "LiveTradingBlocked",
]
